FROM golang:1.16 as builder

WORKDIR /go/src/app
COPY . .

RUN echo "=> start get dependent" \
    && go get -v github.com/go-redis/redis/v8 \
    && go get -v go.uber.org/zap 

RUN echo "=> start compile" \
    && CGO_ENABLED=0 go build .\
    && echo "=> compile complete" 


FROM alpine:3.13
ENV TIME_ZONE=Asia/Shanghai
RUN apk update && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone && \
    apk del tzdata
WORKDIR /root/
COPY --from=builder /go/src/app/free-class .
CMD [ "./free-class" ]
