FROM golang:1.16 as builder

WORKDIR /go/src/app
COPY . .

RUN echo "=> start get dependent" \
    && go get -v github.com/go-redis/redis/v8 \
    && go get -v go.uber.org/zap 
    
RUN echo "=> start compile" \
    && go build --ldflags "-extldflags -static" . \
    && echo "=> compile complete" 


FROM alpine:3.13
WORKDIR /root/
COPY --from=builder /go/src/app/free-class .
CMD [ "free-class" ]
