apiVersion: v1
kind: ConfigMap
metadata:
  name: history-publisher-config
data:
  history-publisher.toml: |
    #[log]
    #stream="stream.log"
    #subject=go-learn.history-publisher

    [database]
    mongo="mongodb://mongodb-svc:27017"
    redis="redis-svc:63791"