apiVersion: batch/v1
kind: CronJob
metadata:
  name: free-class-deployment
spec:
  schedule: "0 5-22/2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: free-class
              image: lyine/free-class:0.3.0
              env:
                - name: REDIS_HOST
                  value: "redis-svc"
                - name: REDIS_PORT
                  value: 6379
