apiVersion: v1
kind: Deployment
metadata:
name: live-status
labels:
  app: live-status
spec:
  replicas: 1
  selector:
    matchLabels:
    app: live-status
  template:
    metadata:
      labels:
        app: live-status
    spec:
      containers:
        - name: live-status
          image: "lyineee/live-notification:0.0.1"
          volumesMounts:
            - name: config
              mountPath: "/etc"
              readOnly: true
          resouces:
            requests:
              cpu: 100m
              memory: 20Mi
  volumes:
    - name: config
      configMap:
        name: live-notification-cm
